FROM ubuntu

RUN apt-get update && \
    apt-get install -y sudo && \
    apt-get install -y ptpd && \
    rm -rf /var/lib/apt/lists/*

RUN adduser root sudo
USER root

CMD sudo ptpd \
    --slave \
    --interface eth0 \
    --domain 0
